# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee4d814c1fb61454314be641db3c7a62c995a6027bad8f17ab9aaa9330687cfe09b1cbd804c18f7af3291666490c14b2cafcc0ed8677773bce6f3412e824636b

test:
  secret_key_base: 67dae6f96ef2f575370dfc718ffa2d629c0846f4782ecbe7c5965ccc8e51c54d15fb8427dd9b6cc2d6855a9e3589852d3e4c534edeef04946632cea2a330b5a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
